export const hiitWorkouts = [
  {
    id: '1',
    name: 'Burpees',
    calories: 12,
    description: 'Full-body explosive movement.',
    icon: 'run-fast',
    steps: [
      'Start in a standing position.',
      'Drop into a squat with hands on the ground.',
      'Kick your feet back into a plank position.',
      'Do a push-up.',
      'Jump your feet forward to return to squat.',
      'Leap into the air and repeat.',
    ],
  },
  {
    id: '2',
    name: 'Mountain Climbers',
    calories: 10,
    description: 'Core and cardio booster.',
    icon: 'arrow-up',
    steps: [
      'Begin in a plank position.',
      'Bring your right knee towards your chest.',
      'Switch legs quickly, pulling left knee in.',
      'Keep hips low and core tight.',
      'Continue alternating rapidly.',
    ],
  },
  {
    id: '3',
    name: 'Jump Squats',
    calories: 11,
    description: 'Legs and glutes power move.',
    icon: 'arrow-up-bold',
    steps: [
      'Stand with feet shoulder-width apart.',
      'Lower into a squat position.',
      'Explode upward into a jump.',
      'Land softly and lower back into a squat.',
      'Repeat immediately.',
    ],
  },
  {
    id: '4',
    name: 'High Knees',
    calories: 9,
    description: 'Intense cardio for legs.',
    icon: 'run',
    steps: [
      'Stand tall with feet hip-width apart.',
      'Lift one knee high toward your chest.',
      'Quickly switch to lift the other knee.',
      'Pump your arms as you move.',
      'Continue alternating knees at a fast pace.',
    ],
  },
  {
    id: '5',
    name: 'Push Ups',
    calories: 8,
    description: 'Upper body strength builder.',
    icon: 'arm-flex',
    steps: [
      'Start in a plank position with hands under shoulders.',
      'Lower your body until your chest almost touches the floor.',
      'Keep elbows close to your body.',
      'Push back up to the starting position.',
      'Repeat with controlled motion.',
    ],
  },
  {
    id: '6',
    name: 'Jumping Jacks',
    calories: 8,
    description: 'Classic full-body warmup.',
    icon: 'human-handsup',
    steps: [
      'Start standing with arms at your sides.',
      'Jump while spreading your legs and raising arms overhead.',
      'Jump again to return to starting position.',
      'Repeat rhythmically.',
    ],
  },
  {
    id: '7',
    name: 'Plank Jacks',
    calories: 7,
    description: 'Core and cardio in one.',
    icon: 'view-dashboard-variant',
    steps: [
      'Begin in a plank position with feet together.',
      'Jump your feet apart and then back together.',
      'Maintain a flat back and engaged core.',
      'Repeat rapidly while staying stable.',
    ],
  },
  {
    id: '8',
    name: 'Skater Jumps',
    calories: 10,
    description: 'Lateral movement for agility.',
    icon: 'skate',
    steps: [
      'Start in a slight squat position.',
      'Jump to the right landing on your right foot.',
      'Cross your left foot behind your right.',
      'Jump to the left landing on your left foot.',
      'Keep alternating sides smoothly.',
    ],
  },
  {
    id: '9',
    name: 'Tuck Jumps',
    calories: 12,
    description: 'Explosive jump for power.',
    icon: 'arrow-up-bold-circle',
    steps: [
      'Stand with knees slightly bent.',
      'Jump up and bring your knees to your chest.',
      'Land softly with bent knees.',
      'Reset and repeat with maximum effort.',
    ],
  },
  {
    id: '10',
    name: 'Sprint in Place',
    calories: 11,
    description: 'Maximum effort cardio.',
    icon: 'run-fast',
    steps: [
      'Stand tall with a slight forward lean.',
      'Run in place as fast as possible.',
      'Pump your arms vigorously.',
      'Keep your knees high and fast.',
      'Maintain speed throughout the duration.',
    ],
  },
];
